@startuml
!define ENTITY class

package "Luggage Import-Export System" {
  ENTITY User {
    +id: int
    username: string
    password: string
    // ... other attributes
  }

  ENTITY Supplier {
    +id: int
    username: string
    password: string
    // ... other attributes
  }

  ENTITY Product {
    +id: int
    name: string
    description: string
    // ... other attributes
  }

  ENTITY Manager {
    +id: int
    username: string
    password: string
    // ... other attributes
  }

  ENTITY Order {
    +id: int
    user: User
    product: Product
    // ... other attributes
  }
}

User --> Order: Places
Supplier --> Product: Supplies
User --> Order: Places
Manager --> Supplier: Approves/Disapproves
Manager --> Product: Approves/Disapproves

@enduml
